version: '3.8'

services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres.rhydtrchiwmnzavezpqb:mashlahore@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
